# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoBrasilDownloader
                                 A QGIS plugin
 Download and load brazilian topographic map sheets from public sources
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-09
        copyright            : (C) 2026 by Renato da Silva
        email                : renatovillela93@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoBrasilDownloader class from file GeoBrasilDownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geobrasil_downloader import GeoBrasilDownloader
    return GeoBrasilDownloader(iface)
