# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoBrasilDownloader
                                 A QGIS plugin
 Download and load brazilian topographic map sheets from public sources
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-09
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Renato da Silva
        email                : renatovillela93@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .geobrasil_downloader_dialog import GeoBrasilDownloaderDialog
import os.path

import os
import webbrowser

from qgis.PyQt.QtWidgets import QTableWidgetItem, QFileDialog
from qgis.core import (
    Qgis,
    QgsProject,
    QgsVectorLayer,
    QgsRasterLayer,
    QgsRectangle,
    QgsGeometry,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
)

import os
import webbrowser
import urllib.request
from urllib.parse import urlparse, unquote

import re
import zipfile
from urllib.parse import urljoin


class GeoBrasilDownloader:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeoBrasilDownloader_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GeoBrasil Downloader')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeoBrasilDownloader', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/geobrasil_downloader/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'GeoBrasil Downloader'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GeoBrasil Downloader'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GeoBrasilDownloaderDialog()
            # GeoBrasil Downloader internal state
            self.ibge_index_layer = None
            self.current_extent_geom = None

            # Connect UI buttons to plugin functions
            self.dlg.btnLoadIndex.clicked.connect(self.load_ibge_index)
            self.dlg.btnUseExtent.clicked.connect(self.use_current_map_extent)
            self.dlg.btnFindSheets.clicked.connect(self.find_sheets)
            self.dlg.btnOpenLink.clicked.connect(self.open_selected_link)
            self.dlg.btnDownloadSelected.clicked.connect(self.download_selected)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
    
    def show_message(self, message, level=Qgis.Info, duration=4):
        """Show a message in the QGIS message bar."""
        self.iface.messageBar().pushMessage(
            "GeoBrasil Downloader",
            message,
            level=level,
            duration=duration
        )


    def load_ibge_index(self):
        """
        Load IBGE Mapa Índice Digital layer(s) from the GeoPackage.

        If 'Search all product types' is checked, load all product layers
        available for the selected scale. Otherwise, load only the selected
        scale/product layer.
        """

        index_path = self.get_ibge_index_path()

        if not os.path.exists(index_path):
            self.show_message(
                "IBGE index not found. Create a data folder and add ibge_mid.gpkg.",
                level=Qgis.Warning,
                duration=8
            )
            return

        selected_scale = self.dlg.comboScale.currentText()
        search_all = self.dlg.checkSearchAllProducts.isChecked()
        layer_map = self.get_ibge_layer_map()

        loaded_layers = []

        if search_all:
            products = self.get_available_products_for_scale(selected_scale)

            for product in products:
                layer_name = layer_map.get((selected_scale, product))

                if layer_name is None:
                    continue

                source = f"{index_path}|layername={layer_name}"

                layer = QgsVectorLayer(
                    source,
                    f"IBGE {selected_scale} - {product}",
                    "ogr"
                )

                if not layer.isValid():
                    continue

                QgsProject.instance().addMapLayer(layer)
                loaded_layers.append(layer)

            if not loaded_layers:
                self.show_message(
                    f"No valid IBGE layers found for {selected_scale}.",
                    level=Qgis.Warning,
                    duration=8
                )
                return

            # Store the first loaded layer as default/current layer
            self.ibge_index_layer = loaded_layers[0]

            total_features = sum(layer.featureCount() for layer in loaded_layers)

            self.show_message(
                f"Loaded {len(loaded_layers)} IBGE product layer(s) for {selected_scale}, with {total_features} total features.",
                level=Qgis.Success,
                duration=8
            )

        else:
            selected_product = self.dlg.comboProduct.currentText()
            layer_name = layer_map.get((selected_scale, selected_product))

            if layer_name is None:
                self.show_message(
                    f"No IBGE layer configured for {selected_scale} / {selected_product}.",
                    level=Qgis.Warning,
                    duration=6
                )
                return

            source = f"{index_path}|layername={layer_name}"

            layer = QgsVectorLayer(
                source,
                f"IBGE {selected_scale} - {selected_product}",
                "ogr"
            )

            if not layer.isValid():
                self.show_message(
                    f"Could not load layer: {layer_name}",
                    level=Qgis.Critical,
                    duration=8
                )
                return

            QgsProject.instance().addMapLayer(layer)
            self.ibge_index_layer = layer

            feature_count = layer.featureCount()

            self.show_message(
                f"Loaded {layer_name} with {feature_count} features.",
                level=Qgis.Success,
                duration=8
            )


    def use_current_map_extent(self):
        """Store the current QGIS map canvas extent as a geometry."""
        canvas = self.iface.mapCanvas()
        extent = canvas.extent()

        canvas_crs = canvas.mapSettings().destinationCrs()

        extent_geom = QgsGeometry.fromRect(
            QgsRectangle(
                extent.xMinimum(),
                extent.yMinimum(),
                extent.xMaximum(),
                extent.yMaximum()
            )
        )

        self.current_extent_geom = extent_geom
        self.current_extent_crs = canvas_crs

        self.show_message(
            "Current map extent stored.",
            level=Qgis.Success,
            duration=4
        )

    def find_sheets(self):
        """
        Find IBGE map sheets that intersect the current QGIS map extent.

        If 'Search all product types' is checked, search all product layers
        available for the selected scale. Otherwise, search only the currently
        loaded layer.
        """

        if self.current_extent_geom is None:
            self.show_message(
                "Click 'Use Current Map Extent' first.",
                level=Qgis.Warning,
                duration=5
            )
            return

        search_all = self.dlg.checkSearchAllProducts.isChecked()
        selected_scale = self.dlg.comboScale.currentText()

        layers_to_search = []

        if search_all:
            layer_map = self.get_ibge_layer_map()
            products = self.get_available_products_for_scale(selected_scale)

            for product in products:
                layer_name = layer_map.get((selected_scale, product))

                if layer_name is None:
                    continue

                layer = self.load_ibge_layer_by_name(layer_name)

                if layer is None:
                    continue

                layers_to_search.append((layer, product, layer_name))

        else:
            if self.ibge_index_layer is None:
                self.show_message(
                    "Load the IBGE index first, or check 'Search all product types'.",
                    level=Qgis.Warning,
                    duration=5
                )
                return

            selected_product = self.dlg.comboProduct.currentText()
            layers_to_search.append(
                (self.ibge_index_layer, selected_product, self.ibge_index_layer.name())
            )

        matches = []

        for layer, product, layer_name in layers_to_search:

            # Copy current extent geometry
            search_geom = QgsGeometry(self.current_extent_geom)

            # Transform current map CRS to current layer CRS if needed
            if self.current_extent_crs != layer.crs():
                transform = QgsCoordinateTransform(
                    self.current_extent_crs,
                    layer.crs(),
                    QgsProject.instance()
                )
                search_geom.transform(transform)

            field_names = [field.name() for field in layer.fields()]

            sheet_field = self.detect_field(
                field_names,
                ["nome", "nome_folha", "folha", "mi", "indice", "codigo", "carta", "inom"]
            )

            scale_field = self.detect_field(
                field_names,
                ["escala", "scale"]
            )

            year_field = self.detect_field(
                field_names,
                ["ano", "ano_publicacao", "publicacao", "year"]
            )

            type_field = self.detect_field(
                field_names,
                ["tipo", "produto", "classe", "categoria", "type"]
            )

            link_field = self.detect_link_field(layer)

            for feature in layer.getFeatures():
                geom = feature.geometry()

                if geom is None or geom.isEmpty():
                    continue

                if not geom.intersects(search_geom):
                    continue

                matches.append({
                    "sheet": self.safe_attr(feature, sheet_field),
                    "scale": self.safe_attr(feature, scale_field),
                    "year": self.safe_attr(feature, year_field),
                    "type": product if product else self.safe_attr(feature, type_field),
                    "link": self.safe_attr(feature, link_field),
                })

        self.populate_results_table(matches)

        if search_all:
            self.show_message(
                f"Found {len(matches)} matching sheet(s) across all product types.",
                level=Qgis.Success if matches else Qgis.Warning,
                duration=8
            )
        else:
            self.show_message(
                f"Found {len(matches)} matching sheet(s).",
                level=Qgis.Success if matches else Qgis.Warning,
                duration=6
            )

    
    def detect_field(self, field_names, candidates):
        """Find a field name using candidate keywords."""
        lower_fields = {name.lower(): name for name in field_names}

        for candidate in candidates:
            candidate = candidate.lower()

            if candidate in lower_fields:
                return lower_fields[candidate]

            for lower_name, original_name in lower_fields.items():
                if candidate in lower_name:
                    return original_name

        return None


    def detect_link_field(self, layer):
        """Detect the first field that appears to contain a URL."""
        field_names = [field.name() for field in layer.fields()]

        possible_link_field = self.detect_field(
            field_names,
            ["download", "link", "url", "ftp", "metadado", "metadata"]
        )

        if possible_link_field:
            return possible_link_field

        for feature in layer.getFeatures():
            for field_name in field_names:
                value = str(feature[field_name])

                if value.startswith("http://") or value.startswith("https://"):
                    return field_name
            break

        return None


    def safe_attr(self, feature, field_name):
        """Safely get an attribute value."""
        if not field_name:
            return ""

        try:
            value = feature[field_name]
        except Exception:
            return ""

        if value is None:
            return ""

        return str(value)


    def populate_results_table(self, matches):
        """Fill the results table with matching sheets."""
        table = self.dlg.tableResults
        table.setRowCount(0)

        for row_index, item in enumerate(matches):
            table.insertRow(row_index)

            table.setItem(row_index, 0, QTableWidgetItem(item["sheet"]))
            table.setItem(row_index, 1, QTableWidgetItem(item["scale"]))
            table.setItem(row_index, 2, QTableWidgetItem(item["year"]))
            table.setItem(row_index, 3, QTableWidgetItem(item["type"]))
            table.setItem(row_index, 4, QTableWidgetItem(item["link"]))

        table.resizeColumnsToContents()

    def open_selected_link(self):
        """Open the selected download link from the results table."""
        table = self.dlg.tableResults
        row = table.currentRow()

        if row < 0:
            self.show_message(
                "Select a row in the results table first.",
                level=Qgis.Warning,
                duration=5
            )
            return

        item = table.item(row, 4)

        if item is None or not item.text().strip():
            self.show_message(
                "No download link found in the selected row.",
                level=Qgis.Warning,
                duration=5
            )
            return

        url = item.text().strip()
        webbrowser.open(url)


    def download_selected(self):
        """Download the selected link from the results table."""
        table = self.dlg.tableResults
        row = table.currentRow()

        if row < 0:
            self.show_message(
                "Select a row in the results table first.",
                level=Qgis.Warning,
                duration=5
            )
            return

        item = table.item(row, 4)

        if item is None or not item.text().strip():
            self.show_message(
                "No download link found in the selected row.",
                level=Qgis.Warning,
                duration=5
            )
            return

        url = item.text().strip()

        # ------------------------------------------------------------------
        # Case 1: selected URL is an IBGE folder page
        # ------------------------------------------------------------------
        if self.is_folder_url(url):
            self.show_message(
                "This is a folder link. Reading available ZIP files...",
                level=Qgis.Info,
                duration=5
            )

            zip_links = self.get_zip_links_from_directory(url)

            if not zip_links:
                self.show_message(
                    "No ZIP files found in this folder. Opening it in your browser.",
                    level=Qgis.Warning,
                    duration=8
                )
                webbrowser.open(url)
                return

            # Simple first version:
            # Download the first ZIP automatically.
            # Later we can improve this by listing ZIP files in the table.
            if len(zip_links) > 1:
                self.show_message(
                    f"Found {len(zip_links)} ZIP files. Downloading the first one for now.",
                    level=Qgis.Warning,
                    duration=8
                )

            url = zip_links[0]

        # ------------------------------------------------------------------
        # Case 2: direct file or ZIP URL
        # ------------------------------------------------------------------
        suggested_name = self.filename_from_url(url)

        save_path, selected_filter = QFileDialog.getSaveFileName(
            self.dlg,
            "Save downloaded file",
            suggested_name,
            "All files (*.*)"
        )

        if not save_path:
            return

        try:
            self.show_message(
                f"Downloading {os.path.basename(save_path)}...",
                level=Qgis.Info,
                duration=5
            )

            urllib.request.urlretrieve(url, save_path)

        except Exception as e:
            self.show_message(
                f"Download failed: {e}",
                level=Qgis.Critical,
                duration=8
            )
            return

        self.show_message(
            f"Downloaded: {os.path.basename(save_path)}",
            level=Qgis.Success,
            duration=5
        )

        # ------------------------------------------------------------------
        # Case 3: downloaded ZIP file
        # ------------------------------------------------------------------
        extension = os.path.splitext(save_path)[1].lower()

        if extension == ".zip":
            extracted_folder = self.extract_zip(save_path)

            if extracted_folder is None:
                return

            self.show_message(
                f"Extracted ZIP to: {os.path.basename(extracted_folder)}",
                level=Qgis.Success,
                duration=5
            )

            if self.dlg.checkAutoLoad.isChecked():
                loaded_count = self.load_gis_files_from_folder(extracted_folder)

                self.show_message(
                    f"Loaded {loaded_count} GIS file(s) from extracted ZIP.",
                    level=Qgis.Success if loaded_count else Qgis.Warning,
                    duration=8
                )

            return

        # ------------------------------------------------------------------
        # Case 4: direct GIS file
        # ------------------------------------------------------------------
        if self.dlg.checkAutoLoad.isChecked():
            self.load_downloaded_file(save_path)
    
    def filename_from_url(self, url):
        """
        Create a suggested filename from a URL.
        If the URL does not end with a filename, use a generic name.
        """

        parsed = urlparse(url)
        filename = os.path.basename(parsed.path)
        filename = unquote(filename)

        if not filename:
            filename = "ibge_download"

        return filename
    
    def get_ibge_layer_map(self):
        """Return IBGE layer mapping by scale and product type."""
        return {
            ("1:1,000,000", "Editoradas"): "Folhas da Carta Internacional do Mundo ao Milionésimo Editoradas",
            ("1:1,000,000", "Vetoriais"): "Folhas da Carta Internacional do Mundo ao Milionésimo Vetoriais",

            ("1:250,000", "Editoradas"): "Folhas Topográficas Editoradas_250k",
            ("1:250,000", "Fotolitos"): "Folhas Topográficas Fotolitos_250k",
            ("1:250,000", "Vetoriais"): "Folhas Topográficas Vetoriais_250k",

            ("1:100,000", "Editoradas"): "Folhas Topográficas Editoradas_100k",
            ("1:100,000", "Fotolitos"): "Folhas Topográficas Fotolitos_100k",
            ("1:100,000", "Vetoriais"): "Folhas Topográficas Vetoriais_100k",
            ("1:100,000", "Cartas Imagem"): "Cartas Imagem_100k",

            ("1:50,000", "Editoradas"): "Folhas Topográficas Editoradas_50k",
            ("1:50,000", "Fotolitos"): "Folhas Topográficas Fotolitos_50k",
            ("1:50,000", "Vetoriais"): "Folhas Topográficas Vetoriais_50k",

            ("1:25,000", "Editoradas"): "Folhas Topográficas Editoradas_25k",
            ("1:25,000", "Fotolitos"): "Folhas Topográficas Fotolitos_25k",
            ("1:25,000", "Vetoriais"): "Folhas Topográficas Vetoriais_25k",
            ("1:25,000", "Cartas Imagem"): "Cartas Imagem_25k",
        }
    
    def get_ibge_index_path(self):
        """Return path to the local IBGE Mapa Índice Digital GeoPackage."""
        plugin_dir = os.path.dirname(__file__)
        return os.path.join(plugin_dir, "data", "ibge_mid.gpkg")
    
    def load_ibge_layer_by_name(self, layer_name):
        """Load an internal IBGE GeoPackage layer by name without adding it to the map."""
        index_path = self.get_ibge_index_path()

        source = f"{index_path}|layername={layer_name}"

        layer = QgsVectorLayer(
            source,
            f"IBGE {layer_name}",
            "ogr"
        )

        if not layer.isValid():
            return None

        return layer
    
    def get_available_products_for_scale(self, scale):
        """Return available product types for the selected scale."""
        layer_map = self.get_ibge_layer_map()

        products = []

        for scale_product, layer_name in layer_map.items():
            map_scale, product = scale_product

            if map_scale == scale:
                products.append(product)

        return products
    
    def load_downloaded_file(self, filepath):
        """Automatically load downloaded GIS files into QGIS."""

        extension = os.path.splitext(filepath)[1].lower()

        # Vector formats
        if extension in [".shp", ".gpkg", ".geojson"]:
            layer = QgsVectorLayer(filepath, os.path.basename(filepath), "ogr")

            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)

                self.show_message(
                    f"Loaded vector layer: {os.path.basename(filepath)}",
                    level=Qgis.Success,
                    duration=5
                )

            else:
                self.show_message(
                    f"Could not load vector layer: {os.path.basename(filepath)}",
                    level=Qgis.Warning,
                    duration=6
                )

        # Raster formats
        elif extension in [".tif", ".tiff"]:
            layer = QgsRasterLayer(filepath, os.path.basename(filepath))

            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)

                self.show_message(
                    f"Loaded raster layer: {os.path.basename(filepath)}",
                    level=Qgis.Success,
                    duration=5
                )

            else:
                self.show_message(
                    f"Could not load raster layer: {os.path.basename(filepath)}",
                    level=Qgis.Warning,
                    duration=6
                )

    def is_folder_url(self, url):
        """Return True if the URL appears to be a directory/folder page."""
        if not url:
            return False

        clean_url = url.strip().lower()

        if clean_url.endswith("/"):
            return True

        parsed = urlparse(clean_url)
        filename = os.path.basename(parsed.path)

        # If there is no extension, it is probably a folder/page
        if "." not in filename:
            return True

        return False
    
    def get_zip_links_from_directory(self, url):
        """
        Read an IBGE directory page and return full URLs to ZIP files.
        This works for simple Apache-style directory listings like IBGE GeoFTP.
        """
        zip_links = []

        try:
            with urllib.request.urlopen(url, timeout=30) as response:
                html = response.read().decode("utf-8", errors="ignore")

        except Exception as e:
            self.show_message(
                f"Could not read folder page: {e}",
                level=Qgis.Warning,
                duration=8
            )
            return zip_links

        # Find href="something.zip" or href='something.zip'
        matches = re.findall(r'href=["\']([^"\']+\.zip)["\']', html, flags=re.IGNORECASE)

        for match in matches:
            full_url = urljoin(url, match)
            zip_links.append(full_url)

        # Remove duplicates while preserving order
        zip_links = list(dict.fromkeys(zip_links))

        return zip_links
    
    def extract_zip(self, zip_path):
        """Extract a ZIP file into a folder with the same base name."""
        output_dir = os.path.splitext(zip_path)[0]
        os.makedirs(output_dir, exist_ok=True)

        try:
            with zipfile.ZipFile(zip_path, "r") as zf:
                zf.extractall(output_dir)

        except Exception as e:
            self.show_message(
                f"Could not extract ZIP file: {e}",
                level=Qgis.Warning,
                duration=8
            )
            return None

        return output_dir
    
    def load_gis_files_from_folder(self, folder_path):
        """Load supported GIS files from a folder and its subfolders."""
        supported_extensions = [".shp", ".gpkg", ".geojson", ".tif", ".tiff"]

        loaded_count = 0

        for root, dirs, files in os.walk(folder_path):
            for filename in files:
                extension = os.path.splitext(filename)[1].lower()

                if extension not in supported_extensions:
                    continue

                filepath = os.path.join(root, filename)
                self.load_downloaded_file(filepath)
                loaded_count += 1

        return loaded_count
